### ISSUE TITLE
关于猫咪问答 Pro Max的日期爆破

### ISSUE THREAD

**Issue by CrystalRays** [USTC-Hackergame/hackergame2021-writeups#61]
emmm，不知道为什么，我在浏览器里用fetch发请求爆破的，设置了setinterval 1000才发了10个请求就告诉我请求过于频繁？？？20秒内爆破两年的日期是在逗我？不过python倒是没试过。。

**Comment by taoky** [comment]
> 设置了setinterval 1000才发了10个请求就告诉我请求过于频繁？？？

猫咪问答没有设置过请求速率限制。具体的代码和错误提示能否提供？

**Comment by CrystalRays** [comment]
不好意思，是我记错题目了，这道题是因为我没有算上2021年的五星社团所以爆破不出来。hackergame时间比较长，那几天参加的比赛有点多记忆混乱了哈哈哈！（好尴尬.jpg）
题解中提到发邮件吐槽的人其实也是我啦！看到题解和出题人的话发现自己给组织者和出题人造成了一定的困扰，在这里道个歉，真的不好意思。其实自己也参与过一些比赛的组织和出题，深能理解出题人和组织者的不易。
另外，其实邮件中提到的关于404页面的问题其实也希望国内的赛事组织者能注意一下，今年早些时候某个大战队（忘了具体哪个战队了2333）的比赛，签到题flag放在了twitter上，着实让人很困扰。虽然作为公民个人行为，法无禁止即可为；但是作为国内安全圈业内有影响力的组织和团体，希望能尊重国家的法律法规和有关措施。


最后附上js写的爆破脚本供参考
```js
d=1;m=1;y=2015;
t=setInterval(()=>{
if(d>31){d=1;m++;};
if(m>12){m=1;y--;};
mm=String(m).padStart(2,"0");
dd=String(d).padStart(2,"0");
fetch("http://202.38.93.111:10001/", {
    method: 'post',
    headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
'Cookie': 'session=****'
    },
    body: `q1=${y}${mm}${dd}&q2=5&q3=Development+Team+of+Library&q4=13&q5=%2Fdev%2Fnull`}).then(res=>res.text()).then(data=>{if(data.search("没有全部答对")<0){clearInterval(t);}})
d++;
},200)
```
